# configs/model_swin_b.yaml
model:
  name: "timm/swin_base_patch4_window7_224"
  num_labels: 2

feature_extractor:
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]
  size: 224
  crop_size: 224
